tconbeer/harlequin

CHANGELOG.md
src/harlequin/tui/app.py
src/harlequin/tui/components/schema_viewer.py
src/harlequin/tui/utils.py

feat: add column types to data table header

---

src/harlequin/tui/app.css
src/harlequin/tui/app.py
tests/functional_tests/test_app.py

fix #103: remove gutter when sidebar is hidden

---

CHANGELOG.md
src/harlequin/tui/app.py
src/harlequin/tui/components/code_editor.py
tests/functional_tests/test_app.py

fix #82: change fmt key binding; add alt for ctrl+b

---

poetry.lock
pyproject.toml
src/harlequin/tui/app.css
src/harlequin/tui/app.py

- fix #115: add CSS for limit checkbox
- fix #109: add scrollbar CSS for TextContainer

Fix CSS for limit checkbox, scrollbar

---

CHANGELOG.md
src/harlequin/tui/app.css
src/harlequin/tui/app.py
src/harlequin/tui/components/__init__.py
src/harlequin/tui/components/code_editor.py
src/harlequin/tui/components/error_modal.py
src/harlequin/tui/components/help_screen.md
src/harlequin/tui/components/help_screen.py
tests/functional_tests/test_app.py

feat: add help screen, add focus bindings

---

CHANGELOG.md
src/harlequin/tui/app.css
src/harlequin/tui/app.py
src/harlequin/tui/components/__init__.py
src/harlequin/tui/components/export_screen.py
src/harlequin/tui/components/help_screen.md
src/harlequin/tui/components/path_suggester.py
tests/functional_tests/test_app.py

feat: export data to csv, parquet, or json file

---

CHANGELOG.md
src/harlequin/cli.py
src/harlequin/duck_ops.py
src/harlequin/tui/app.py
tests/functional_tests/test_duck_ops.py

feat: add extension options, support prql

---

CHANGELOG.md
src/harlequin/tui/app.py
src/harlequin/tui/components/results_viewer.py
tests/conftest.py
tests/functional_tests/test_app.py

- fix: refactor use of workers, fix loading state
- fix: use pilot.pause() to await cpu idle in tests
- chore: update changelog

Loading state fix

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/harlequin/cache.py
src/harlequin/tui/app.py
src/harlequin/tui/components/code_editor.py
tests/functional_tests/test_app.py
tests/functional_tests/test_cache.py

Closes #175
- Bumps version to 0.0.27
- chore: update changelog and readme
- fix: changelog typo
- feat: cache current buffers to restore state on restart

Cache and restore buffer state

---

CHANGELOG.md
debug.svg
src/harlequin/tui/app.py
tests/functional_tests/test_app.py

fix #196: stop cursor blink under modal

---

.pre-commit-config.yaml
CHANGELOG.md
poetry.lock
pyproject.toml
src/harlequin/app.py
src/harlequin/components/code_editor.py
src/harlequin/global.tcss

- feat: add notifications for query time, save, clipboard error
- fix: improve clipboard error msg
closes #226 
closes #235

Add notifications for query timing, save, and clipboard error

---

CHANGELOG.md
src/harlequin/app.py

- fix #268: ignore queries with only whitespace
- chore: update changelog

fix #268: ignore queries with only whitespace

---

CHANGELOG.md
plugins/harlequin_duckdb/__init__.py
plugins/harlequin_duckdb/adapter.py
plugins/harlequin_duckdb/cli_options.py
src/harlequin/adapter.py
src/harlequin/cli.py
src/harlequin/options.py
tests/adapter_tests/tests/test_duckdb.py
tests/unit_tests/test_cli.py

refactor: dynamically load CLI opts; add adapter opt

---

CHANGELOG.md
plugins/harlequin_duckdb/__init__.py
plugins/harlequin_duckdb/adapter.py
plugins/harlequin_duckdb/copy_formats.py
src/harlequin/adapter.py
src/harlequin/app.py
src/harlequin/components/export_screen.py
src/harlequin/copy_widgets.py
src/harlequin/global.tcss
src/harlequin/options.py
tests/adapter_tests/tests/test_duckdb.py

refactor: dynamically load copy options

---

CHANGELOG.md
poetry.lock
pyproject.toml
tests/functional_tests/test_app.py

see https://github.com/tconbeer/textual-fastdatatable/issues/26

fix: bump fastdatatable to handle dupe col names; add test

---

CHANGELOG.md
plugins/harlequin_duckdb/adapter.py
src/harlequin/components/results_viewer.py
tests/functional_tests/test_app.py

fix: display list types and map types

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/harlequin/app.py
src/harlequin/exception.py
src/harlequin/global.tcss

Refactor db connect to use worker

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/harlequin/config_wizard.py

fix #404: guard against adapters with no options

---

.github/workflows/publish.yml

follows https://til.simonwillison.net/pypi/pypi-releases-from-github

refactor: use PyPI trusted publishing

---

.github/workflows/static.yml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/harlequin/app.py
src/harlequin/components/data_catalog.py
src/harlequin/export.py
src/harlequin/options.py
src/harlequin_duckdb/adapter.py
tests/functional_tests/test_app.py

fix #568: bump fastdatatable to fix datetime overflow error

---

CHANGELOG.md
src/harlequin/app.py

fix #609: only focus results viewer if data

---

CHANGELOG.md
poetry.lock
pyproject.toml

fix #654: bump textarea to fix gotoline crash

---

CHANGELOG.md
poetry.lock
pyproject.toml

fix #649: bump textarea for better copy/paste error handling

---

tests/functional_tests/test_query_editor.py

fix #742: add more waits while expanding data catalog nodes

---

CHANGELOG.md
poetry.lock
pyproject.toml

fix #754: update numpy pin

---

README.md

Closes #808 for real this time.

Fix two more links in README
